name: RigelMCMod
main: me.rigelmc.rigelmcmod.RigelMCMod
version: ${tfm.build.version}
description: Plugin for the RigelMC server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, RMC-Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza, LightWarp, OxLemonxO]

# plugin.yml is no longer used to define commands.
