name: RigelMCMod
main: me.rigelmc.rigelmcmod.RigelMCMod
version: 2.2
description: Plugin for the RigelMC server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, RMC-Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza, LightWarp, OxLemonxO, _Fleek]

# plugin.yml is no longer used to define commands.
